package codehub.core.permissions

object DangerousCommandPatterns {

    data class DangerousMatch(
        val patternKey: String,
        val description: String,
        val severity: Severity
    )

    enum class Severity { Warn, Dangerous, Catastrophic }

    data class Pattern(
        val key: String,
        val regex: Regex,
        val description: String,
        val severity: Severity
    )

    val patterns: List<Pattern> = listOf(
        Pattern("rm_rf_root", Regex("""\brm\s+(?:-[a-zA-Z]*r[a-zA-Z]*f?|-[a-zA-Z]*f[a-zA-Z]*r)\s+(?:--no-preserve-root\s+)?/(?:\s|$|\*)"""), "Recursive delete targeting filesystem root", Severity.Catastrophic),
        Pattern("rm_rf_home", Regex("""\brm\s+(?:-[a-zA-Z]*r[a-zA-Z]*f?|-[a-zA-Z]*f[a-zA-Z]*r)\s+(?:~|${'$'}HOME)(?:\s|$)"""), "Recursive delete of home directory", Severity.Catastrophic),
        Pattern("rm_rf_wildcard", Regex("""\brm\s+(?:-[a-zA-Z]*r[a-zA-Z]*f?|-[a-zA-Z]*f[a-zA-Z]*r)\s+\*\.(?:so|apk|dex|jar|class|o|a|exe)"""), "Recursive delete of build artifacts", Severity.Dangerous),
        Pattern("rm_force_no_prompt", Regex("""\brm\s+.*-f.*\s"""), "Forced file deletion without prompt", Severity.Warn),
        Pattern("mkfs_any", Regex("""\bmkfs(?:\.\w+)?\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Filesystem format on block device", Severity.Catastrophic),
        Pattern("dd_to_device", Regex("""\bdd\s+if=.*\s+of=/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Raw write to block device", Severity.Catastrophic),
        Pattern("dd_from_dev", Regex("""\bdd\s+if=/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Raw read from block device", Severity.Dangerous),
        Pattern("chmod_777", Regex("""\bchmod\s+(?:-R\s+)?777\b"""), "World-writable recursive chmod", Severity.Warn),
        Pattern("chmod_777_path", Regex("""\bchmod\s+(?:-R\s+)?777\s+/(?:etc|usr|bin|sbin|system|boot|root)"""), "chmod 777 on system path", Severity.Catastrophic),
        Pattern("chown_root", Regex("""\bchown\s+(?:-R\s+)?root(?::\w+)?\s+/(?:etc|usr|bin|sbin|system)"""), "Recursive chown to root on system path", Severity.Dangerous),
        Pattern("curl_pipe_sh", Regex("""\b(?:curl|wget)\s+(?:-[a-zA-Z]+\s+)*https?://[^\s|]+\s*\|\s*(?:sh|bash|zsh|python(?:3)?|perl)\b"""), "Remote script piped to interpreter", Severity.Catastrophic),
        Pattern("curl_pipe_sudo_sh", Regex("""\b(?:curl|wget)\s+(?:-[a-zA-Z]+\s+)*https?://[^\s|]+\s*\|\s*sudo\s+(?:sh|bash)"""), "Remote script piped to sudo interpreter", Severity.Catastrophic),
        Pattern("base64_decode_bash", Regex("""\bbase64\s+(?:-[a-zA-Z]+\s+)*-d(?:ecode)?\s*\|\s*(?:sh|bash|zsh)"""), "Base64-encoded payload piped to shell", Severity.Catastrophic),
        Pattern("wget_pipe_sh", Regex("""\bwget\s+(?:-[a-zA-Z]+\s+)*-O\s+-\s+https?://[^\s|]+\s*\|\s*(?:sh|bash)"""), "Wget output piped to shell", Severity.Catastrophic),
        Pattern("fork_bomb", Regex(""":\(\)\s*\{\s*:\|:\s*&\s*\}\s*;:"""), "Fork bomb", Severity.Catastrophic),
        Pattern("fork_bomb_alt", Regex("""\bbash\s+-c\s+['"]?\(\)\s*\{.*\|.*&.*\}"""), "Fork bomb variant", Severity.Catastrophic),
        Pattern("kill_all_processes", Regex("""\bkill(?:all)?\s+-9\s+-1\b"""), "Kill all processes", Severity.Catastrophic),
        Pattern("kill_init", Regex("""\bkill\s+-9\s+(?:1|0)\b"""), "Kill init process", Severity.Catastrophic),
        Pattern("pkill_pattern", Regex("""\bpkill\s+-9\s+(?:-f\s+)?(?:.*\*)"""), "Wildcard pkill", Severity.Dangerous),
        Pattern("killall_system", Regex("""\bkillall\s+(?:-9\s+)?(?:system_server|zygote|surfaceflinger)"""), "Kill critical Android processes", Severity.Catastrophic),
        Pattern("shutdown_cmd", Regex("""\b(?:shutdown|poweroff|halt|reboot)\b"""), "System shutdown or reboot", Severity.Dangerous),
        Pattern("systemctl_stop_critical", Regex("""\bsystemctl\s+(?:stop|disable|kill)\s+(?:sshd|networking|systemd-networkd|dbus|systemd-udevd)"""), "Stop critical system service", Severity.Dangerous),
        Pattern("systemctl_mask", Regex("""\bsystemctl\s+mask\s+"""), "Mask systemd unit", Severity.Warn),
        Pattern("docker_rm_container", Regex("""\bdocker\s+(?:container\s+)?rm\s+-f\b"""), "Force-remove Docker container", Severity.Warn),
        Pattern("docker_rm_image", Regex("""\bdocker\s+(?:image\s+)?rmi\s+-f\b"""), "Force-remove Docker image", Severity.Warn),
        Pattern("docker_stop_all", Regex("""\bdocker\s+stop\s+\$\(\s*docker\s+ps\s+-q\s*\)"""), "Stop all Docker containers", Severity.Dangerous),
        Pattern("docker_system_prune", Regex("""\bdocker\s+system\s+prune\s+(?:-a|--all)"""), "Prune all Docker resources", Severity.Dangerous),
        Pattern("git_push_force", Regex("""\bgit\s+push\s+(?:--force|-f)\b"""), "Force-push to remote", Severity.Dangerous),
        Pattern("git_push_force_lease", Regex("""\bgit\s+push\s+--force-with-lease(?::[^[:space:]]+)?\b"""), "Force-push with lease (still destructive)", Severity.Warn),
        Pattern("git_reset_hard", Regex("""\bgit\s+reset\s+--hard\b"""), "Hard reset discards uncommitted work", Severity.Dangerous),
        Pattern("git_clean_force", Regex("""\bgit\s+clean\s+-[a-zA-Z]*fd"""), "Force-clean untracked files and directories", Severity.Dangerous),
        Pattern("git_branch_delete_force", Regex("""\bgit\s+branch\s+-D\b"""), "Force-delete branch", Severity.Warn),
        Pattern("git_rebase_master", Regex("""\bgit\s+rebase\s+(?:--(?:onto|root)\s+)?(?:origin/)?(?:master|main)\b"""), "Rebase onto main (history rewrite risk)", Severity.Warn),
        Pattern("git_filter_branch", Regex("""\bgit\s+filter-branch\b"""), "Rewrite history (slow, destructive)", Severity.Dangerous),
        Pattern("find_delete", Regex("""\bfind\s+/(?:[^\s]+\s+)*-delete\b"""), "Find with -delete on root", Severity.Catastrophic),
        Pattern("find_delete_home", Regex("""\bfind\s+~(?:\s+[^\s]+)*\s+-delete\b"""), "Find with -delete on home", Severity.Dangerous),
        Pattern("find_exec_rm", Regex("""\bfind\s+.*-exec\s+rm\s+"""), "Find with -exec rm", Severity.Dangerous),
        Pattern("truncate_device", Regex("""\btruncate\s+-s\s+0\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Truncate block device to zero", Severity.Catastrophic),
        Pattern("shred_device", Regex("""\bshred\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Shred block device", Severity.Catastrophic),
        Pattern("mv_to_dev_null", Regex("""\bmv\s+\S+\s+/dev/null\b"""), "Move file to /dev/null", Severity.Warn),
        Pattern("redirect_to_dev_null_root", Regex("""\b>\s*/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Redirect output to block device", Severity.Catastrophic),
        Pattern("sql_drop_database", Regex("""\bDROP\s+(?:DATABASE|SCHEMA)\b""", RegexOption.IGNORE_CASE), "SQL DROP DATABASE", Severity.Dangerous),
        Pattern("sql_drop_table", Regex("""\bDROP\s+TABLE\b""", RegexOption.IGNORE_CASE), "SQL DROP TABLE", Severity.Dangerous),
        Pattern("sql_drop_table_no_where", Regex("""\bDELETE\s+FROM\s+(?:(?!\bWHERE\b).)*$""", RegexOption.IGNORE_CASE), "SQL DELETE without WHERE", Severity.Dangerous),
        Pattern("sql_truncate", Regex("""\bTRUNCATE\s+TABLE\b""", RegexOption.IGNORE_CASE), "SQL TRUNCATE", Severity.Dangerous),
        Pattern("sudo_any", Regex("""\bsudo\s+"""), "Sudo invocation", Severity.Warn),
        Pattern("sudo_rm", Regex("""\bsudo\s+rm\b"""), "Sudo rm", Severity.Dangerous),
        Pattern("sudo_chmod", Regex("""\bsudo\s+chmod\b"""), "Sudo chmod", Severity.Warn),
        Pattern("sudo_chown", Regex("""\bsudo\s+chown\b"""), "Sudo chown", Severity.Warn),
        Pattern("sudo_dd", Regex("""\bsudo\s+dd\b"""), "Sudo dd", Severity.Catastrophic),
        Pattern("sudo_mkfs", Regex("""\bsudo\s+mkfs\b"""), "Sudo mkfs", Severity.Catastrophic),
        Pattern("sudo_reboot", Regex("""\bsudo\s+(?:reboot|shutdown|halt|poweroff)"""), "Sudo system shutdown", Severity.Dangerous),
        Pattern("su_root", Regex("""\bsu\s+-\s*root\b"""), "Switch to root user", Severity.Warn),
        Pattern("su_dash", Regex("""\bsu\s+-\s*$"""), "Switch to root user (su -)", Severity.Warn),
        Pattern("adb_remount", Regex("""\badb\s+remount\b"""), "ADB remount system partition", Severity.Dangerous),
        Pattern("adb_root", Regex("""\badb\s+root\b"""), "ADB root access", Severity.Warn),
        Pattern("adb_install_unknown", Regex("""\badb\s+install\s+.*http"""), "ADB install from URL (suspicious)", Severity.Warn),
        Pattern("fastboot_flash", Regex("""\bfastboot\s+flash\s+"""), "Fastboot flash partition", Severity.Dangerous),
        Pattern("fastboot_erase", Regex("""\bfastboot\s+erase\s+"""), "Fastboot erase partition", Severity.Catastrophic),
        Pattern("fastboot_format", Regex("""\bfastboot\s+format\s+"""), "Fastboot format partition", Severity.Dangerous),
        Pattern("iptables_flush", Regex("""\biptables\s+-F\b"""), "Flush firewall rules", Severity.Dangerous),
        Pattern("iptables_drop_all", Regex("""\biptables\s+-A\s+(?:INPUT|OUTPUT|FORWARD)\s+-j\s+DROP"""), "Drop all traffic", Severity.Dangerous),
        Pattern("npm_uninstall_global", Regex("""\bnpm\s+uninstall\s+-g\b"""), "Global npm uninstall", Severity.Warn),
        Pattern("npm_force_uninstall", Regex("""\bnpm\s+uninstall\s+--force"""), "Force npm uninstall", Severity.Warn),
        Pattern("pip_uninstall_yes", Regex("""\bpip(?:3)?\s+uninstall\s+-y\b"""), "Pip uninstall without prompt", Severity.Warn),
        Pattern("apt_purge", Regex("""\bapt(?:-get)?\s+(?:purge|autoremove)\s+--purge"""), "APT purge", Severity.Warn),
        Pattern("apt_remove", Regex("""\bapt(?:-get)?\s+remove\s+--yes"""), "APT remove without prompt", Severity.Warn),
        Pattern("pip_install_no_deps", Regex("""\bpip(?:3)?\s+install\s+--no-deps"""), "Pip install without dependencies", Severity.Warn),
        Pattern("chmod_executable_download", Regex("""\bchmod\s+\+x\s+.*\.(?:sh|py|pl|rb)\b"""), "Make downloaded script executable", Severity.Warn),
        Pattern("eval_remote", Regex("""\beval\s+\$\(\s*(?:curl|wget)\s"""), "Eval remote content", Severity.Catastrophic),
        Pattern("source_remote", Regex("""\bsource\s+\$\(\s*(?:curl|wget)\s"""), "Source remote script", Severity.Catastrophic),
        Pattern("exec_remote", Regex("""\bexec\s+\$\(\s*(?:curl|wget)\s"""), "Exec remote command", Severity.Catastrophic),
        Pattern("wget_no_check_cert", Regex("""\bwget\s+--no-check-certificate"""), "Wget without TLS verification", Severity.Warn),
        Pattern("curl_insecure", Regex("""\bcurl\s+-k\b|\bcurl\s+--insecure\b"""), "Curl without TLS verification", Severity.Warn),
        Pattern("ssh_no_strict", Regex("""\bssh\s+(?:-o\s+)?StrictHostKeyChecking=no"""), "SSH without host key check", Severity.Warn),
        Pattern("scp_no_strict", Regex("""\bscp\s+.*StrictHostKeyChecking=no"""), "SCP without host key check", Severity.Warn),
        Pattern("rsync_no_strict", Regex("""\brsync\s+-e\s+['"]?ssh.*StrictHostKeyChecking=no"""), "Rsync without host key check", Severity.Warn),
        Pattern("export_path_overwrite", Regex("""\bexport\s+PATH\s*=\s*[^:$]"""), "Overwrite PATH (instead of append)", Severity.Warn),
        Pattern("unset_path", Regex("""\bunset\s+PATH\b"""), "Unset PATH variable", Severity.Dangerous),
        Pattern("cd_dev_null", Regex("""\bcd\s+/dev/null\b"""), "Cd into /dev/null", Severity.Warn),
        Pattern("redirect_overwrite_passwd", Regex(""">\s*/etc/(?:passwd|shadow|group|sudoers)"""), "Overwrite system auth file", Severity.Catastrophic),
        Pattern("redirect_overwrite_hosts", Regex(""">\s*/etc/hosts\b"""), "Overwrite /etc/hosts", Severity.Dangerous),
        Pattern("redirect_overwrite_fstab", Regex(""">\s*/etc/fstab\b"""), "Overwrite /etc/fstab", Severity.Catastrophic),
        Pattern("tee_system_file", Regex("""\btee\s+/(?:etc|usr|bin|sbin|system)/(?:[^\s|]+)"""), "Tee to system file", Severity.Dangerous),
        Pattern("mount_overwrite", Regex("""\bmount\s+-o\s+remount,rw\s+/system\b"""), "Remount /system read-write", Severity.Dangerous),
        Pattern("magisk_uninstall", Regex("""\bmagisk\s+--uninstall\b"""), "Uninstall Magisk root", Severity.Dangerous),
        Pattern("setenforce_zero", Regex("""\bsetenforce\s+0\b"""), "Disable SELinux", Severity.Dangerous),
        Pattern("set_prop_persist", Regex("""\bsetprop\s+persist\."""), "Set persistent Android property", Severity.Warn),
        Pattern("settings_put_secure", Regex("""\bsettings\s+put\s+(?:secure|global)\s"""), "Modify Android secure/global setting", Severity.Warn),
        Pattern("pm_clear", Regex("""\bpm\s+clear\s"""), "Clear app data", Severity.Warn),
        Pattern("pm_uninstall_system", Regex("""\bpm\s+uninstall\s+--user\s+0\s+com\.android\."""), "Uninstall system app for user", Severity.Dangerous),
        Pattern("pm_disable_system", Regex("""\bpm\s+disable\s+com\.android\."""), "Disable system app", Severity.Dangerous),
        Pattern("cmd_package_uninstall", Regex("""\bcmd\s+package\s+uninstall"""), "Cmd package uninstall", Severity.Warn),
        Pattern("input_keycode_power", Regex("""\binput\s+keyevent\s+(?:26|6)"""), "Simulate power/home key", Severity.Warn),
        Pattern("am_force_stop", Regex("""\bam\s+force-stop\s+com\.android\."""), "Force-stop system app", Severity.Warn),
        Pattern("am_kill_background", Regex("""\bam\s+kill\s+background"""), "Kill all background processes", Severity.Dangerous),
        Pattern("wm_density_reset", Regex("""\bwm\s+density\s+reset"""), "Reset display density", Severity.Warn),
        Pattern("wm_size_reset", Regex("""\bwm\s+size\s+reset"""), "Reset display size", Severity.Warn),
        Pattern("settings_reset_secure", Regex("""\bsettings\s+reset\s+secure"""), "Reset all secure settings", Severity.Dangerous),
        Pattern("rm_modprobe", Regex("""\brmmod\s+(?:snd|video|usb|net|wifi|bluetooth)"""), "Unload kernel module", Severity.Dangerous),
        Pattern("insmod_unknown", Regex("""\binsmod\s+/data/"""), "Load kernel module from /data", Severity.Dangerous),
        Pattern("dev_mem_access", Regex("""\b(?:dd|cat|xxd)\s+.*\s+/dev/mem\b"""), "Access /dev/mem", Severity.Catastrophic),
        Pattern("dev_kmem_access", Regex("""\b(?:dd|cat|xxd)\s+.*\s+/dev/kmem\b"""), "Access /dev/kmem", Severity.Catastrophic),
        Pattern("proc_kallsyms", Regex("""\bcat\s+/proc/kallsyms\s*>\s*/data/"""), "Dump kernel symbols to file", Severity.Warn),
        Pattern("root_certificate_install", Regex("""\bcp\s+.*\.(?:crt|pem|cer)\s+/system/etc/security/cacerts/"""), "Install root certificate to system store", Severity.Dangerous),
        Pattern("iptables_masquerade", Regex("""\biptables\s+-t\s+nat\s+-A\s+POSTROUTING\s+-j\s+MASQUERADE"""), "Enable NAT masquerade", Severity.Warn),
        Pattern("ifconfig_down", Regex("""\bifconfig\s+\w+\s+down\b"""), "Bring network interface down", Severity.Dangerous),
        Pattern("ip_link_set_down", Regex("""\bip\s+link\s+set\s+\w+\s+down\b"""), "Bring link down", Severity.Dangerous),
        Pattern("nmcli_con_delete", Regex("""\bnmcli\s+connection\s+delete"""), "Delete network connection", Severity.Warn),
        Pattern("hostname_change", Regex("""\bhostname\s+(?:-S\s+)?[a-zA-Z]"""), "Change hostname", Severity.Warn),
        Pattern("userdel_root", Regex("""\buserdel\s+(?:-r\s+)?root\b"""), "Delete root user", Severity.Catastrophic),
        Pattern("usermod_root_shell", Regex("""\busermod\s+-s\s+/bin/(?:sh|bash)\s+root\b"""), "Modify root user shell", Severity.Dangerous),
        Pattern("passwd_force", Regex("""\bpasswd\s+-d\b"""), "Delete user password", Severity.Dangerous),
        Pattern("chmod_suid_binary", Regex("""\bchmod\s+[45]755\s+/usr/(?:bin|sbin|local/bin)"""), "Set SUID on system binary", Severity.Dangerous),
        Pattern("cron_remove", Regex("""\bcrontab\s+-r\b"""), "Remove crontab", Severity.Warn),
        Pattern("atq_remove", Regex("""\batrm\s+"""), "Remove queued job", Severity.Warn),
        Pattern("systemctl_disable_critical", Regex("""\bsystemctl\s+disable\s+(?:sshd|NetworkManager|systemd-networkd|systemd-resolved|dbus)"""), "Disable critical service", Severity.Dangerous),
        Pattern("umount_root", Regex("""\bumount\s+/(?:system|data|boot|vendor)"""), "Unmount critical Android partition", Severity.Dangerous),
        Pattern("mount_tmpfs_root", Regex("""\bmount\s+-t\s+tmpfs\s+none\s+/"""), "Mount tmpfs over root", Severity.Catastrophic),
        Pattern("losetup_delete", Regex("""\blosetup\s+-d\s+/dev/loop0"""), "Detach loop device", Severity.Warn),
        Pattern("mdadm_stop", Regex("""\bmdadm\s+--stop\s+/dev/md"""), "Stop RAID array", Severity.Dangerous),
        Pattern("vgremove", Regex("""\bvgremove\s+-f"""), "Force-remove LVM volume group", Severity.Dangerous),
        Pattern("lvremove", Regex("""\blvremove\s+-f"""), "Force-remove LVM logical volume", Severity.Dangerous),
        Pattern("pvremove", Regex("""\bpvremove\s+-f"""), "Force-remove LVM physical volume", Severity.Dangerous),
        Pattern("parted_mklabel", Regex("""\bparted\s+.*mklabel\b"""), "Repartition disk (destroy partition table)", Severity.Catastrophic),
        Pattern("fdisk_delete", Regex("""\bfdisk\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Run fdisk on block device", Severity.Dangerous),
        Pattern("gdisk_delete", Regex("""\bgdisk\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Run gdisk on block device", Severity.Dangerous),
        Pattern("wipefs", Regex("""\bwipefs\s+-a\b"""), "Wipe all filesystem signatures", Severity.Catastrophic),
        Pattern("sfdisk", Regex("""\bsfdisk\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Run sfdisk on block device", Severity.Dangerous),
        Pattern("hdparm_security", Regex("""\bhdparm\s+--security-erase"""), "ATA secure erase disk", Severity.Catastrophic),
        Pattern("hdparm_security_unlock", Regex("""\bhdparm\s+--security-unlock"""), "ATA security unlock disk", Severity.Warn),
        Pattern("xfs_repair_force", Regex("""\bxfs_repair\s+-L"""), "Force XFS log zeroing", Severity.Dangerous),
        Pattern("e2fsck_force", Regex("""\be2fsck\s+-f\s+-y"""), "Force fsck with auto-yes", Severity.Dangerous),
        Pattern("resize2fs_device", Regex("""\bresize2fs\s+/dev/"""), "Resize filesystem on device", Severity.Dangerous),
        Pattern("tune2fs_device", Regex("""\btune2fs\s+/dev/"""), "Modify filesystem parameters on device", Severity.Dangerous),
        Pattern("docker_volume_rm", Regex("""\bdocker\s+volume\s+rm\s+(?:-f|--force)"""), "Force-remove Docker volume", Severity.Warn),
        Pattern("docker_network_disconnect", Regex("""\bdocker\s+network\s+disconnect\s+-f"""), "Force-disconnect Docker network", Severity.Warn),
        Pattern("docker_swarm_leave", Regex("""\bdocker\s+swarm\s+leave\s+--force"""), "Force-leave Docker swarm", Severity.Warn),
        Pattern("kubernetes_delete_all", Regex("""\bkubectl\s+delete\s+(?:pods|deployments|services|namespaces)\s+--all"""), "Delete all Kubernetes resources", Severity.Dangerous),
        Pattern("kubectl_delete_namespace", Regex("""\bkubectl\s+delete\s+namespace\s+(?:default|kube-system|kube-public)"""), "Delete critical K8s namespace", Severity.Dangerous),
        Pattern("helm_uninstall", Regex("""\bhelm\s+uninstall\s+.*--no-hooks"""), "Helm uninstall without hooks", Severity.Warn),
        Pattern("terraform_destroy", Regex("""\bterraform\s+destroy\s+--force"""), "Force-destroy Terraform state", Severity.Dangerous),
        Pattern("ansible_ad_hoc_command", Regex("""\bansible\s+all\s+-m\s+shell\s+-a"""), "Ansible ad-hoc shell command on all hosts", Severity.Warn),
        Pattern("vagrant_destroy", Regex("""\bvagrant\s+destroy\s+-f"""), "Force-destroy Vagrant VM", Severity.Warn),
        Pattern("virtualbox_unregistervm", Regex("""\bVBoxManage\s+unregistervm\s+--delete"""), "Delete VirtualBox VM", Severity.Warn),
        Pattern("qemu_img_create_overwrite", Regex("""\bqemu-img\s+create\s+-f\s+qcow2\s+/dev/(?:sd|nvme|vd|hd)"""), "Create QCOW2 on block device", Severity.Catastrophic),
        Pattern("dd_recovery", Regex("""\bdd\s+if=/dev/zero\s+of=/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Zero-fill block device", Severity.Catastrophic),
        Pattern("cat_to_device", Regex("""\bcat\s+\S+\s*>\s*/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Cat file to block device", Severity.Catastrophic),
        Pattern("echo_to_device", Regex("""\becho\s+['"]?[^'"]*['"]?\s*>\s*/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Echo to block device", Severity.Catastrophic),
        Pattern("tee_device", Regex("""\btee\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Tee to block device", Severity.Catastrophic),
        Pattern("tar_extract_root", Regex("""\btar\s+(?:-xzf|-xvjf|-xf)\s+\S+\s+-C\s+/(?:etc|usr|bin|sbin|boot|system)"""), "Extract tar to system path", Severity.Dangerous),
        Pattern("unzip_to_system", Regex("""\bunzip\s+\S+\s+-d\s+/(?:etc|usr|bin|sbin|boot|system)"""), "Unzip to system path", Severity.Dangerous),
        Pattern("cp_to_system", Regex("""\bcp\s+(?:-r\s+)?\S+\s+/(?:etc|usr/bin|usr/sbin|boot|system)/(?:[^\s|]+)"""), "Copy file to system path", Severity.Dangerous),
        Pattern("rsync_to_system", Regex("""\brsync\s+(?:-a\s+)?--delete\s+.*\s+/(?:etc|usr|bin|sbin|boot|system)"""), "Rsync with --delete to system path", Severity.Catastrophic),
        Pattern("scp_to_remote_root", Regex("""\bscp\s+\S+\s+root@\S+:/"""), "SCP to remote root path", Severity.Warn),
        Pattern("rsync_delete_remote", Regex("""\brsync\s+.*--delete\s+.*root@\S+:"""), "Rsync delete on remote root", Severity.Dangerous),
        Pattern("make_clean_dist", Regex("""\bmake\s+(?:distclean|mrproper)\b"""), "Make distclean (removes configure script too)", Severity.Warn),
        Pattern("make_uninstall_global", Regex("""\bmake\s+uninstall(?:\s+PREFIX=/usr)?"""), "Make uninstall to system prefix", Severity.Dangerous),
        Pattern("cmake_install_to_system", Regex("""\bcmake\s+--install\s+(?:--prefix\s+)?/(?:usr|etc|opt)"""), "CMake install to system prefix", Severity.Dangerous),
        Pattern("meson_setup_with_rebuild", Regex("""\bmeson\s+setup\s+--wipe\b"""), "Meson setup with --wipe (forces rebuild)", Severity.Warn),
        Pattern("cargo_install_force", Regex("""\bcargo\s+install\s+--force"""), "Cargo install --force", Severity.Warn),
        Pattern("go_mod_tidy_with_cache", Regex("""\bgo\s+clean\s+-modcache"""), "Clean Go module cache", Severity.Warn),
        Pattern("python_rmtree_site_packages", Regex("""\brm\s+-rf\s+(?:--no-preserve-root\s+)?/usr/lib/python\d+/site-packages"""), "Remove Python site-packages", Severity.Dangerous),
        Pattern("dotnet_nuget_force", Regex("""\bdotnet\s+nuget\s+locals\s+all\s+--clear"""), "Clear all NuGet caches", Severity.Warn),
        Pattern("gradle_clean_project", Regex("""\bgradle\s+clean\s+--refresh-dependencies"""), "Gradle clean with refresh", Severity.Warn),
        Pattern("xcodebuild_clean", Regex("""\bxcodebuild\s+clean"""), "Xcode clean", Severity.Warn),
        Pattern("npm_cache_clean_force", Regex("""\bnpm\s+cache\s+clean\s+--force"""), "NPM cache clean --force", Severity.Warn),
        Pattern("yarn_cache_clean", Regex("""\byarn\s+cache\s+clean"""), "Yarn cache clean", Severity.Warn),
        Pattern("pnpm_store_prune", Regex("""\bpnpm\s+store\s+prune"""), "pnpm store prune", Severity.Warn),
        Pattern("brew_uninstall", Regex("""\bbrew\s+uninstall\s+--force"""), "Homebrew force uninstall", Severity.Warn),
        Pattern("apt_autoremove_purge", Regex("""\bapt(?:-get)?\s+autoremove\s+--purge"""), "APT autoremove with purge", Severity.Warn),
        Pattern("snap_remove", Regex("""\bsnap\s+remove\s+--purge"""), "Snap remove with purge", Severity.Warn),
        Pattern("flatpak_uninstall_user", Regex("""\bflatpak\s+uninstall\s+--user\s+--delete-data"""), "Flatpak uninstall with data", Severity.Warn),
        Pattern("rm_android_data", Regex("""\brm\s+-rf\s+/data/data/com\.termux"""), "Remove Termux data directory", Severity.Catastrophic),
        Pattern("rm_android_system_app", Regex("""\brm\s+-rf\s+/system/app/"""), "Remove Android system app", Severity.Catastrophic),
        Pattern("rm_android_priv_app", Regex("""\brm\s+-rf\s+/system/priv-app/"""), "Remove Android priv-app", Severity.Catastrophic),
        Pattern("rm_android_vendor", Regex("""\brm\s+-rf\s+/vendor/"""), "Remove Android vendor partition content", Severity.Catastrophic),
        Pattern("rm_android_system_lib", Regex("""\brm\s+-rf\s+/system/lib(?:64)?/"""), "Remove Android system libraries", Severity.Catastrophic),
        Pattern("rm_android_framework", Regex("""\brm\s+-rf\s+/system/framework/"""), "Remove Android framework", Severity.Catastrophic),
        Pattern("rm_init_d", Regex("""\brm\s+-rf\s+/etc/init\.d/"""), "Remove init.d scripts", Severity.Dangerous),
        Pattern("rm_systemd_unit", Regex("""\brm\s+-rf\s+/etc/systemd/system/"""), "Remove systemd units", Severity.Dangerous),
        Pattern("rm_cron", Regex("""\brm\s+-rf\s+/etc/cron\.(d|hourly|daily|weekly|monthly)"""), "Remove cron directories", Severity.Dangerous),
        Pattern("crontab_overwrite", Regex("""\bcrontab\s+.*>\s+/etc/crontab"""), "Overwrite system crontab", Severity.Dangerous),
        Pattern("rm_authorized_keys", Regex("""\brm\s+-f\s+~?/?\.ssh/authorized_keys"""), "Remove SSH authorized keys", Severity.Dangerous),
        Pattern("cat_to_authorized_keys", Regex("""\b(?:cat|echo)\s+.*\s*>>?\s*~?/?\.ssh/authorized_keys"""), "Write to SSH authorized_keys", Severity.Warn),
        Pattern("chmod_ssh_key_world", Regex("""\bchmod\s+6\d\d\s+~?/?\.ssh/id_"""), "Loosen SSH key permissions", Severity.Dangerous),
        Pattern("ssh_keygen_remove", Regex("""\bssh-keygen\s+-R\b"""), "Remove SSH host key", Severity.Warn),
        Pattern("gpg_delete_secret", Regex("""\bgpg\s+--delete-secret-keys"""), "Delete GPG secret keys", Severity.Dangerous),
        Pattern("gpg_delete_secret_and_pub", Regex("""\bgpg\s+--delete-secret-and-public-keys"""), "Delete GPG secret and public keys", Severity.Dangerous),
        Pattern("openssl_dgst_dev", Regex("""\bopenssl\s+dgst\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "OpenSSL digest on block device (suspicious)", Severity.Warn),
        Pattern("openssl_enc_inplace", Regex("""\bopenssl\s+enc\s+.*-in\s+/etc/(?:passwd|shadow)"""), "Encrypt system auth file in place", Severity.Catastrophic),
        Pattern("tar_extract_dev_null", Regex("""\btar\s+.*--to-command=/bin/(?:sh|bash)"""), "Tar extract with shell command", Severity.Dangerous),
        Pattern("cpio_extract_root", Regex("""\bcpio\s+-idmv\s+.*<\s*/dev/"""), "Cpio extract from device", Severity.Warn),
        Pattern("find_exec_pip", Regex("""\bfind\s+.*-exec\s+(?:pip|npm|cargo)\s+install"""), "Find with package manager install", Severity.Warn),
        Pattern("find_exec_git_clone", Regex("""\bfind\s+.*-exec\s+git\s+clone"""), "Find with git clone (suspicious)", Severity.Warn),
        Pattern("find_exec_curl", Regex("""\bfind\s+.*-exec\s+curl"""), "Find with curl (suspicious)", Severity.Warn),
        Pattern("xargs_rm", Regex("""\bxargs\s+rm\b"""), "Xargs with rm", Severity.Dangerous),
        Pattern("xargs_pip_uninstall", Regex("""\bxargs\s+pip\s+uninstall"""), "Xargs with pip uninstall", Severity.Warn),
        Pattern("parallel_rm", Regex("""\bparallel\s+rm\b"""), "GNU parallel with rm", Severity.Dangerous),
        Pattern("find_exec_chmod_exec", Regex("""\bfind\s+.*-exec\s+chmod\s+\+x"""), "Find with chmod +x", Severity.Warn),
        Pattern("find_exec_chown_root", Regex("""\bfind\s+.*-exec\s+chown\s+root"""), "Find with chown root", Severity.Dangerous),
        Pattern("find_delete_xdev", Regex("""\bfind\s+.*-xdev\s+.*-delete"""), "Find with -xdev and -delete", Severity.Dangerous),
        Pattern("chmod_minus_R_root", Regex("""\bchmod\s+-R\s+[0-7]+\s+/"""), "Recursive chmod from root", Severity.Catastrophic),
        Pattern("chown_minus_R_root", Regex("""\bchown\s+-R\s+"""), "Recursive chown", Severity.Warn),
        Pattern("chgrp_minus_R_root", Regex("""\bchgrp\s+-R\s+"""), "Recursive chgrp", Severity.Warn),
        Pattern("umount_minus_a", Regex("""\bumount\s+-a\b"""), "Unmount all filesystems", Severity.Catastrophic),
        Pattern("umount_force_lazy", Regex("""\bumount\s+-l\s+/(?:system|data|boot|vendor)"""), "Lazy unmount of critical partition", Severity.Dangerous),
        Pattern("mount_minus_a", Regex("""\bmount\s+-a\b"""), "Mount all from fstab", Severity.Dangerous),
        Pattern("mount_minus_o_loop_root", Regex("""\bmount\s+-o\s+loop.*\s+/"""), "Loop mount on root path", Severity.Dangerous),
        Pattern("debugfs_device", Regex("""\bdebugfs\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Run debugfs on block device", Severity.Dangerous),
        Pattern("file_device", Regex("""\bfile\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Inspect block device (suspicious)", Severity.Warn),
        Pattern("hexdump_device", Regex("""\b(?:hexdump|xxd|od)\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Hexdump block device (suspicious)", Severity.Warn),
        Pattern("strings_device", Regex("""\bstrings\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Strings on block device (suspicious)", Severity.Warn),
        Pattern("grep_device", Regex("""\bgrep\s+.*\s+/dev/(?:sd|nvme|vd|hd|mmcblk)"""), "Grep on block device (suspicious)", Severity.Warn),
        Pattern("cat_kmsg", Regex("""\bcat\s+/dev/kmsg\s*>\s*/data/"""), "Dump kernel messages to file", Severity.Warn),
        Pattern("dmesg_clear", Regex("""\bdmesg\s+-C\b"""), "Clear kernel ring buffer", Severity.Warn),
        Pattern("sysctl_modify", Regex("""\bsysctl\s+-w\s+"""), "Modify kernel parameter", Severity.Warn),
        Pattern("sysctl_kernel_random", Regex("""\bsysctl\s+-w\s+kernel\.random\."""), "Modify kernel random parameters", Severity.Dangerous),
        Pattern("sysctl_net_ipv4_forward", Regex("""\bsysctl\s+-w\s+net\.ipv4\.ip_forward=0"""), "Disable IP forwarding", Severity.Warn),
        Pattern("ip_route_flush", Regex("""\bip\s+route\s+flush\s+all"""), "Flush all routes", Severity.Dangerous),
        Pattern("ip_addr_flush", Regex("""\bip\s+addr\s+flush\s+dev"""), "Flush device addresses", Severity.Dangerous),
        Pattern("ip_neigh_flush", Regex("""\bip\s+neigh\s+flush\s+all"""), "Flush all neighbors", Severity.Warn),
        Pattern("arp_flush", Regex("""\barp\s+-d\s+\*"""), "Flush ARP cache", Severity.Warn),
        Pattern("macchanger_random", Regex("""\bmacchanger\s+-A"""), "Randomize MAC", Severity.Warn),
        Pattern("aircrack_deauth", Regex("""\bairodump-ng\s+-w\s+"""), "Aircrack-ng capture (suspicious)", Severity.Warn),
        Pattern("aireplay_deauth", Regex("""\baireplay-ng\s+--deauth"""), "WiFi deauth attack", Severity.Dangerous),
        Pattern("nmap_aggressive", Regex("""\bnmap\s+-A\s+"""), "Aggressive Nmap scan", Severity.Warn),
        Pattern("nmap_syn_scan", Regex("""\bnmap\s+-sS\s+"""), "SYN scan", Severity.Warn),
        Pattern("masscan_full_range", Regex("""\bmasscan\s+.*--rate\s+\d{4,}"""), "Masscan high-rate scan", Severity.Warn),
        Pattern("hydra_attack", Regex("""\bhydra\s+-L\s+.*-P"""), "Hydra brute force attack", Severity.Dangerous),
        Pattern("john_password", Regex("""\bjohn\s+--wordlist"""), "John the Ripper password crack", Severity.Warn),
        Pattern("hashcat_dictionary", Regex("""\bhashcat\s+-a\s+0\s+.*-m"""), "Hashcat dictionary attack", Severity.Warn),
        Pattern("sqlmap_dump", Regex("""\bsqlmap\s+.*--dump"""), "SQLmap data dump", Severity.Dangerous),
        Pattern("metasploit_run", Regex("""\bmsfconsole\s+-x\s+"""), "Metasploit run", Severity.Dangerous),
        Pattern("ettercap_mitm", Regex("""\bettercap\s+-T\s+-M\s+/arp"""), "Ettercap ARP MITM", Severity.Dangerous),
        Pattern("tcpdump_iface_promiscuous", Regex("""\btcpdump\s+-i\s+\w+\s+-w\s+.*-U"""), "Tcpdump promiscuous capture", Severity.Warn),
        Pattern("tshark_capture", Regex("""\btshark\s+-i\s+\w+\s+-w"""), "Tshark capture", Severity.Warn),
        Pattern("bettercap_run", Regex("""\bbettercap\s+-caplet"""), "Bettercap run with caplet", Severity.Warn),
        Pattern("wifite_run", Regex("""\bwifite\s+--kill"""), "Wifite with --kill", Severity.Dangerous),
        Pattern("reaver_run", Regex("""\breaver\s+-i\s+.*-b\s+"""), "Reaver WPA attack", Severity.Dangerous),
        Pattern("bully_run", Regex("""\bbully\s+.*-b\s+"""), "Bully WPA attack", Severity.Dangerous),
        Pattern("fern_wifi_cracker", Regex("""\bfern-wifi-cracker"""), "Fern WiFi cracker", Severity.Dangerous),
        Pattern("kismet_capture", Regex("""\bkismet\s+.*-c\s+"""), "Kismet capture", Severity.Warn),
        Pattern("beef_run", Regex("""\bbeef-xss"""), "BeEF XSS framework", Severity.Dangerous),
        Pattern("setoolkit_run", Regex("""\bsetoolkit"""), "Social Engineer's Toolkit", Severity.Dangerous),
        Pattern("armitage_run", Regex("""\barmitage"""), "Armitage (Metasploit GUI)", Severity.Dangerous),
        Pattern("maltego_run", Regex("""\bmaltego"""), "Maltego OSINT", Severity.Warn),
        Pattern("theharvester_run", Regex("""\btheHarvester\s+-d\s+"""), "theHarvester OSINT", Severity.Warn),
        Pattern("sherlock_run", Regex("""\bsherlock\s+\w"""), "Sherlock username search", Severity.Warn),
        Pattern("recon_ng_run", Regex("""\brecon-ng"""), "Recon-ng framework", Severity.Warn),
        Pattern("spiderfoot_run", Regex("""\bspiderfoot\s+-s\s+"""), "SpiderFoot OSINT", Severity.Warn)
    )

    fun evaluate(command: String): DangerousMatch? {
        for (pattern in patterns) {
            if (pattern.regex.containsMatchIn(command)) {
                return DangerousMatch(
                    patternKey = pattern.key,
                    description = pattern.description,
                    severity = pattern.severity
                )
            }
        }
        return null
    }

    fun isDangerous(command: String): Boolean = evaluate(command) != null

    val catastrophicPatternKeys: Set<String> = patterns
        .filter { it.severity == Severity.Catastrophic }
        .map { it.key }
        .toSet()

    val dangerousPatternKeys: Set<String> = patterns
        .filter { it.severity == Severity.Dangerous }
        .map { it.key }
        .toSet()
}
